-- 1. Tables with NO Foreign Keys (Must be created first)
CREATE TABLE FACULTIES (
  id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  faculty_name NVARCHAR(MAX) NOT NULL
);

CREATE TABLE ADMISSION_PROJECTS (
  id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  project_name NVARCHAR(MAX) NOT NULL
);

CREATE TABLE STUDY_PLANS (
  id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  plan_group NVARCHAR(MAX),
  plan_name NVARCHAR(MAX) NOT NULL
);

CREATE TABLE SUBJECTS (
  id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  subject_type NVARCHAR(MAX),
  subject_name NVARCHAR(MAX) NOT NULL
);

-- 2. Tables with 1st Level Dependencies
CREATE TABLE DEPARTMENTS (
  id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  dept_name NVARCHAR(MAX) NOT NULL,
  faculty_id BIGINT,
  CONSTRAINT FK_DEPARTMENTS_FACULTIES FOREIGN KEY (faculty_id) REFERENCES FACULTIES(id)
);

CREATE TABLE USERS (
  id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  citizen_id NVARCHAR(100) NOT NULL UNIQUE,
  password NVARCHAR(MAX) NOT NULL,
  role NVARCHAR(MAX) DEFAULT 'student',
  first_name NVARCHAR(MAX) NOT NULL,
  last_name NVARCHAR(MAX) NOT NULL,
  edu_status NVARCHAR(MAX),
  current_level DECIMAL(18,2),
  gpax_5_term DECIMAL(18,2),
  plan_id BIGINT,
  high_school NVARCHAR(MAX),
  CONSTRAINT FK_USERS_PLANS FOREIGN KEY (plan_id) REFERENCES STUDY_PLANS(id)
);

-- 3. Tables with 2nd Level Dependencies
CREATE TABLE PROGRAMS (
  id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  prog_name NVARCHAR(MAX) NOT NULL,
  dept_id BIGINT,
  CONSTRAINT FK_PROGRAMS_DEPARTMENTS FOREIGN KEY (dept_id) REFERENCES DEPARTMENTS(id)
);

CREATE TABLE USER_SCORES (
  user_id BIGINT NOT NULL,
  subject_id BIGINT NOT NULL,
  score_value DECIMAL(18,2),
  exam_year DECIMAL(18,2),
  total_credits DECIMAL(18,2),
  CONSTRAINT PK_USER_SCORES PRIMARY KEY (user_id, subject_id),
  CONSTRAINT FK_SCORES_USERS FOREIGN KEY (user_id) REFERENCES USERS(id),
  CONSTRAINT FK_SCORES_SUBJECTS FOREIGN KEY (subject_id) REFERENCES SUBJECTS(id)
);

-- 4. Tables with 3rd Level Dependencies
CREATE TABLE ADMISSION_CRITERIA (
  id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  academic_year DECIMAL(18,2),
  tcas_round SMALLINT,
  max_seats INT,
  min_gpax DECIMAL(18,2),
  start_date DATETIMEOFFSET,
  end_date DATETIMEOFFSET,
  program_id BIGINT,
  project_id BIGINT,
  edu_status_req NVARCHAR(MAX),
  min_level NVARCHAR(MAX),
  max_level NVARCHAR(MAX),
  CONSTRAINT FK_CRITERIA_PROGRAMS FOREIGN KEY (program_id) REFERENCES PROGRAMS(id),
  CONSTRAINT FK_CRITERIA_PROJECTS FOREIGN KEY (project_id) REFERENCES ADMISSION_PROJECTS(id)
);

-- 5. Tables with 4th Level Dependencies (The Connectors)
CREATE TABLE APPLICATION (
  id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  payment_status NVARCHAR(50) DEFAULT 'pending',
  application_date DATETIMEOFFSET DEFAULT SYSDATETIMEOFFSET(),
  status NVARCHAR(50) DEFAULT 'pending',
  transcript_url NVARCHAR(MAX),
  portfolio_url NVARCHAR(MAX),
  gpax DECIMAL(18,2),
  criteria_id BIGINT,
  user_id BIGINT,
  CONSTRAINT FK_APPLICATION_CRITERIA FOREIGN KEY (criteria_id) REFERENCES ADMISSION_CRITERIA(id),
  CONSTRAINT FK_APPLICATION_USERS FOREIGN KEY (user_id) REFERENCES USERS(id)
);

CREATE TABLE CRITERIA_PLANS (
  criteria_id BIGINT NOT NULL,
  plan_id BIGINT NOT NULL,
  CONSTRAINT PK_CRITERIA_PLANS PRIMARY KEY (criteria_id, plan_id),
  CONSTRAINT FK_CP_CRITERIA FOREIGN KEY (criteria_id) REFERENCES ADMISSION_CRITERIA(id),
  CONSTRAINT FK_CP_PLANS FOREIGN KEY (plan_id) REFERENCES STUDY_PLANS(id)
);

CREATE TABLE CRITERIA_SUBJECTS (
  criteria_id BIGINT NOT NULL,
  subject_id BIGINT NOT NULL,
  weight DECIMAL(18,2),
  min_score DECIMAL(18,2),
  min_credits DECIMAL(18,2),
  CONSTRAINT PK_CRITERIA_SUBJECTS PRIMARY KEY (criteria_id, subject_id),
  CONSTRAINT FK_CS_CRITERIA FOREIGN KEY (criteria_id) REFERENCES ADMISSION_CRITERIA(id),
  CONSTRAINT FK_CS_SUBJECTS FOREIGN KEY (subject_id) REFERENCES SUBJECTS(id)
);